
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
     app: frontend
    tier: web
    project: expense
  template: 
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: frontend:1.0 # change to your docker hub image and version
        #ports:
        #- containerPort: 8080
       

---

# service in manifest.yaml is written in the same namespace as deployment, so it will be created in the same namespace as deployment . service is used to expose the deployment to other pods in the same namespace or to external clients.

kind: Service
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend port
    protocol: TCP
    port: 80 # service port
    targetport: 80 # container port defined in deployment